language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: DCH5l2IYaxNmUtai9TTv10iWUOV7M+uSlrVLGkBGb1isavu7qWPXjj9oM7hX80nu5gdiDHCWPUYfbQBBufTskXQ8Gc6leTZ1G0JAxR0UVzu5y3p2b15FW5RkM9xwMNF6Ar9lsjo4aRCzMu1RIjwTFBMLJkTfVGWYDGc2KVtrz/pV6EPJq8FnUnvdPr5yz6Wylx6uzQ5eifv1cVYDh7deuY8iegCtzEXR4Y+iGwQJImb9RUvLYnRB7wBAHxBF8gW5QuBLer18MH15DP/CJ0ymWhoDdsGaETwGiz6pSQXf4dj0W8QP3Pre7OIvEQ11WCAjjaPFxrds9IIlzjvTODCzpX815RdULGiWwYyQatB+C6cY/tyd7qll0TlNY70N+b6CbfTLuqjEwVlPN5ckEWJ2X4TcPqu/GF0kOU4K+HdSi16qzD+7nmkLqxYxGbtEdXJI2+BIBs6uMkrgbW2yh+abbN98nJQdRedRBy2A0G+WNATjbP5m3ZAxjAp1F6TOYoxB6lRRI6xusnbaVP3bhojzs9bo7QXSHI695dC/Lrm10T6AR+SJXPiPpbjjksoeINgUMHHbTmzWpXEeJWMtGWr8h1VZ057h/eZOUmL8NknGNWGegXgB5qrUvJqDGx7t/koZ/R7gdU+SC72Ma/SfTFBBOG7dARwX3mDiUMogcBk83Rk=
  app: sanni-test1